# Generated by Django 3.2.13 on 2023-01-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('hashtag', models.CharField(blank=True, max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='좋아요')),
                ('hearts', models.PositiveIntegerField(default=0, verbose_name='하트')),
                ('funny', models.PositiveIntegerField(default=0, verbose_name='웃겨요')),
                ('sad', models.PositiveIntegerField(default=0, verbose_name='슬퍼요')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='조회수')),
            ],
        ),
    ]
