# Generated by Django 3.2.13 on 2023-01-06 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryarticle',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diaryarticle',
            name='funny',
            field=models.PositiveIntegerField(default=0, verbose_name='웃겨요'),
        ),
        migrations.AddField(
            model_name='diaryarticle',
            name='hearts',
            field=models.PositiveIntegerField(default=0, verbose_name='하트'),
        ),
        migrations.AddField(
            model_name='diaryarticle',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AddField(
            model_name='diaryarticle',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='좋아요'),
        ),
        migrations.AddField(
            model_name='diaryarticle',
            name='sad',
            field=models.PositiveIntegerField(default=0, verbose_name='슬퍼요'),
        ),
        migrations.AddField(
            model_name='diaryarticle',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
