# Generated by Django 3.2.13 on 2023-01-12 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='diary_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.diaryarticle'),
        ),
    ]
